from itertools import combinations

from node import Node
from collections import deque


class Graph:
    def __init__(self):
        self.nodes = []

    def get_distances_from_node(self, node_name):
        # Create a dictionary to hold distances
        distances = {node.name: float('inf') for node in self.nodes}
        distances[node_name] = 0

        # Create a queue for BFS
        queue = deque([node_name])

        while queue:
            current_node_name = queue.popleft()
            current_distance = distances[current_node_name]

            # Get the neighbors of the current node
            current_node_neighbors = self.probe_node(current_node_name)

            for neighbor in current_node_neighbors:
                if distances[neighbor] == float('inf'):  # Not visited yet
                    distances[neighbor] = current_distance + 1
                    queue.append(neighbor)

        return distances

    def compute_distance_matrix(self):
        distance_matrix = {}
        for node in self.nodes:
            distance_matrix[node.name] = self.get_distances_from_node(node.name)
        return distance_matrix

    def get_metric_dimension(self):
        distance_matrix = self.compute_distance_matrix()

        for r in range(1, len(self.nodes) + 1):
            for candidate_set in combinations(self.nodes, r):
                if is_resolving_set(self, candidate_set, distance_matrix):
                    return r, [node.name for node in candidate_set]

        return None

    def probe_node(self, node_name):
        for node in self.nodes:
            if node_name == node.name:
                return node.get_neighbors()

    def add_node(self, node):
        self.nodes.append(node)


def is_resolving_set(graph, candidate_set, distance_matrix):
    all_distances = []

    for node in graph.nodes:
        distances = tuple(distance_matrix[node.name][cand.name] for cand in candidate_set)
        all_distances.append(distances)

    return len(all_distances) == len(set(all_distances))


def create_franklin_graph():
    franklin_graph = Graph()

    a = Node("A", ["B", "C", "E"])
    b = Node("B", ["A", "D", "H"])
    c = Node("C", ["A", "F", "J"])
    d = Node("D", ["B", "G", "I"])
    e = Node("E", ["A", "F", "K"])
    f = Node("F", ["C", "E", "G"])
    g = Node("G", ["D", "F", "H"])
    h = Node("H", ["B", "G", "L"])
    i = Node("I", ["D", "J", "K"])
    j = Node("J", ["C", "I", "L"])
    k = Node("K", ["E", "I", "L"])
    l = Node("L", ["H", "J", "K"])

    franklin_graph.add_node(a)
    franklin_graph.add_node(b)
    franklin_graph.add_node(c)
    franklin_graph.add_node(d)
    franklin_graph.add_node(e)
    franklin_graph.add_node(f)
    franklin_graph.add_node(g)
    franklin_graph.add_node(h)
    franklin_graph.add_node(i)
    franklin_graph.add_node(j)
    franklin_graph.add_node(k)
    franklin_graph.add_node(l)

    return franklin_graph


def create_first_loupekine_snark():
    first_loupekine_snark = Graph()

    a = Node("A", ["B", "C", "K"])
    b = Node("B", ["A", "F", "O"])
    c = Node("C", ["A", "H", "L"])
    d = Node("D", ["E", "G", "L"])
    e = Node("E", ["D", "J", "N"])
    f = Node("F", ["B", "I", "N"])
    g = Node("G", ["D", "H", "K"])
    h = Node("H", ["C", "G", "M"])
    i = Node("I", ["F", "J", "M"])
    j = Node("J", ["E", "I", "O"])
    k = Node("K", ["A", "G", "U"])
    l = Node("L", ["C", "D", "Q"])
    m = Node("M", ["H", "I", "P"])
    n = Node("N", ["E", "F", "R"])
    o = Node("O", ["B", "J", "V"])
    p = Node("P", ["M", "S", "T"])
    q = Node("Q", ["L", "R", "T"])
    r = Node("R", ["N", "Q", "S"])
    s = Node("S", ["P", "R", "U"])
    t = Node("T", ["P", "Q", "V"])
    u = Node("U", ["K", "S", "V"])
    v = Node("V", ["O", "T", "U"])

    first_loupekine_snark.add_node(a)
    first_loupekine_snark.add_node(b)
    first_loupekine_snark.add_node(c)
    first_loupekine_snark.add_node(d)
    first_loupekine_snark.add_node(e)
    first_loupekine_snark.add_node(f)
    first_loupekine_snark.add_node(g)
    first_loupekine_snark.add_node(h)
    first_loupekine_snark.add_node(i)
    first_loupekine_snark.add_node(j)
    first_loupekine_snark.add_node(k)
    first_loupekine_snark.add_node(l)
    first_loupekine_snark.add_node(m)
    first_loupekine_snark.add_node(n)
    first_loupekine_snark.add_node(o)
    first_loupekine_snark.add_node(p)
    first_loupekine_snark.add_node(q)
    first_loupekine_snark.add_node(r)
    first_loupekine_snark.add_node(s)
    first_loupekine_snark.add_node(t)
    first_loupekine_snark.add_node(u)
    first_loupekine_snark.add_node(v)

    return first_loupekine_snark


def create_double_star_snark():
    double_star_snark = Graph()

    node1 = Node("1", ["2", "9", "27"])
    node2 = Node("2", ["1", "3", "5"])
    node3 = Node("3", ["2", "7", "25"])
    node4 = Node("4", ["5", "18", "24"])
    node5 = Node("5", ["2", "4", "6"])
    node6 = Node("6", ["5", "16", "22"])
    node7 = Node("7", ["3", "8", "15"])
    node8 = Node("8", ["7", "9", "11"])
    node9 = Node("9", ["1", "8", "13"])
    node10 = Node("10", ["11", "24", "30"])
    node11 = Node("11", ["8", "10", "12"])
    node12 = Node("12", ["11", "22", "28"])
    node13 = Node("13", ["9", "14", "21"])
    node14 = Node("14", ["13", "15", "17"])
    node15 = Node("15", ["7", "14", "19"])
    node16 = Node("16", ["6", "17", "30"])
    node17 = Node("17", ["14", "16", "18"])
    node18 = Node("18", ["4", "17", "28"])
    node19 = Node("19", ["15", "20", "27"])
    node20 = Node("20", ["19", "21", "23"])
    node21 = Node("21", ["13", "20", "25"])
    node22 = Node("22", ["6", "12", "23"])
    node23 = Node("23", ["20", "22", "24"])
    node24 = Node("24", ["4", "10", "23"])
    node25 = Node("25", ["3", "21", "26"])
    node26 = Node("26", ["25", "27", "29"])
    node27 = Node("27", ["1", "19", "26"])
    node28 = Node("28", ["12", "18", "29"])
    node29 = Node("29", ["26", "28", "30"])
    node30 = Node("30", ["10", "16", "29"])

    double_star_snark.add_node(node1)
    double_star_snark.add_node(node2)
    double_star_snark.add_node(node3)
    double_star_snark.add_node(node4)
    double_star_snark.add_node(node5)
    double_star_snark.add_node(node6)
    double_star_snark.add_node(node7)
    double_star_snark.add_node(node8)
    double_star_snark.add_node(node9)
    double_star_snark.add_node(node10)
    double_star_snark.add_node(node11)
    double_star_snark.add_node(node12)
    double_star_snark.add_node(node13)
    double_star_snark.add_node(node14)
    double_star_snark.add_node(node15)
    double_star_snark.add_node(node16)
    double_star_snark.add_node(node17)
    double_star_snark.add_node(node18)
    double_star_snark.add_node(node19)
    double_star_snark.add_node(node20)
    double_star_snark.add_node(node21)
    double_star_snark.add_node(node22)
    double_star_snark.add_node(node23)
    double_star_snark.add_node(node24)
    double_star_snark.add_node(node25)
    double_star_snark.add_node(node26)
    double_star_snark.add_node(node27)
    double_star_snark.add_node(node28)
    double_star_snark.add_node(node29)
    double_star_snark.add_node(node30)

    return double_star_snark


def create_szekeres_snark():
    szekeres_snark = Graph()

    node1 = Node('A', ['B', 'E', 'C'])
    node2 = Node('B', ['D', 'O', 'A'])
    node3 = Node('C', ['A', 'N', 'F'])
    node4 = Node('D', ['KK', 'G', 'B'])
    node5 = Node('E', ['A', 'G', 'H'])
    node6 = Node('F', ['C', 'H', 'LL'])
    node7 = Node('G', ['D', 'E', 'N'])
    node8 = Node('H', ['F', 'E', 'O'])
    node9 = Node('I', ['K', 'M', 'J'])
    node10 = Node('J', ['I', 'P', 'L'])
    node11 = Node('K', ['Q', 'Y', 'I'])
    node12 = Node('L', ['J', 'Z', 'R'])
    node13 = Node('M', ['I', 'S', 'U'])
    node14 = Node('N', ['G', 'C', 'Z'])
    node15 = Node('O', ['B', 'H', 'Y'])
    node16 = Node('P', ['V', 'J', 'T'])
    node17 = Node('Q', ['W', 'K', 'S'])
    node18 = Node('R', ['L', 'T', 'X'])
    node19 = Node('S', ['Q', 'M', 'BB'])
    node20 = Node('T', ['P', 'R', 'CC'])
    node21 = Node('U', ['M', 'W', 'II'])
    node22 = Node('V', ['P', 'X', 'JJ'])
    node23 = Node('W', ['Q', 'AA', 'U'])
    node24 = Node('X', ['R', 'DD', 'V'])
    node25 = Node('Y', ['K', 'BB', 'O'])
    node26 = Node('Z', ['N', 'L', 'CC'])
    node27 = Node('AA', ['W', 'BB', 'TT'])
    node28 = Node('BB', ['AA', 'S', 'Y'])
    node29 = Node('CC', ['Z', 'T', 'DD'])
    node30 = Node('DD', ['CC', 'X', 'SS'])
    node31 = Node('EE', ['KK', 'FF', 'MM'])
    node32 = Node('FF', ['EE', 'GG', 'WW'])
    node33 = Node('GG', ['FF', 'HH', 'XX'])
    node34 = Node('HH', ['GG', 'LL', 'NN'])
    node35 = Node('II', ['U', 'QQ', 'OO'])
    node36 = Node('JJ', ['V', 'RR', 'PP'])
    node37 = Node('KK', ['D', 'EE', 'QQ'])
    node38 = Node('LL', ['F', 'HH', 'RR'])
    node39 = Node('MM', ['EE', 'UU', 'OO'])
    node40 = Node('NN', ['PP', 'HH', 'VV'])
    node41 = Node('OO', ['II', 'MM', 'SS'])
    node42 = Node('PP', ['JJ', 'NN', 'TT'])
    node43 = Node('QQ', ['KK', 'II', 'UU'])
    node44 = Node('RR', ['JJ', 'LL', 'VV'])
    node45 = Node('SS', ['OO', 'DD', 'WW'])
    node46 = Node('TT', ['PP', 'AA', 'XX'])
    node47 = Node('UU', ['QQ', 'MM', 'WW'])
    node48 = Node('VV', ['NN', 'XX', 'RR'])
    node49 = Node('WW', ['FF', 'UU', 'SS'])
    node50 = Node('XX', ['TT', 'GG', 'VV'])

    szekeres_snark.add_node(node1)
    szekeres_snark.add_node(node2)
    szekeres_snark.add_node(node3)
    szekeres_snark.add_node(node4)
    szekeres_snark.add_node(node5)
    szekeres_snark.add_node(node6)
    szekeres_snark.add_node(node7)
    szekeres_snark.add_node(node8)
    szekeres_snark.add_node(node9)
    szekeres_snark.add_node(node10)
    szekeres_snark.add_node(node11)
    szekeres_snark.add_node(node12)
    szekeres_snark.add_node(node13)
    szekeres_snark.add_node(node14)
    szekeres_snark.add_node(node15)
    szekeres_snark.add_node(node16)
    szekeres_snark.add_node(node17)
    szekeres_snark.add_node(node18)
    szekeres_snark.add_node(node19)
    szekeres_snark.add_node(node20)
    szekeres_snark.add_node(node21)
    szekeres_snark.add_node(node22)
    szekeres_snark.add_node(node23)
    szekeres_snark.add_node(node24)
    szekeres_snark.add_node(node25)
    szekeres_snark.add_node(node26)
    szekeres_snark.add_node(node27)
    szekeres_snark.add_node(node28)
    szekeres_snark.add_node(node29)
    szekeres_snark.add_node(node30)
    szekeres_snark.add_node(node31)
    szekeres_snark.add_node(node32)
    szekeres_snark.add_node(node33)
    szekeres_snark.add_node(node34)
    szekeres_snark.add_node(node35)
    szekeres_snark.add_node(node36)
    szekeres_snark.add_node(node37)
    szekeres_snark.add_node(node38)
    szekeres_snark.add_node(node39)
    szekeres_snark.add_node(node40)
    szekeres_snark.add_node(node41)
    szekeres_snark.add_node(node42)
    szekeres_snark.add_node(node43)
    szekeres_snark.add_node(node44)
    szekeres_snark.add_node(node45)
    szekeres_snark.add_node(node46)
    szekeres_snark.add_node(node47)
    szekeres_snark.add_node(node48)
    szekeres_snark.add_node(node49)
    szekeres_snark.add_node(node50)

    return szekeres_snark


def create_second_blanusa_snark():
    second_blanusa_snark = Graph()

    node1 = Node("A", ["B", "C", "E"])
    node2 = Node("B", ["A", "D", "K"])
    node3 = Node("C", ["A", "M", "N"])
    node4 = Node("D", ["B", "P", "Q"])
    node5 = Node("E", ["A", "F", "L"])
    node6 = Node("F", ["E", "G", "N"])
    node7 = Node("G", ["F", "H", "M"])
    node8 = Node("H", ["G", "I", "O"])
    node9 = Node("I", ["H", "J", "Q"])
    node10 = Node("J", ["I", "K", "P"])
    node11 = Node("K", ["B", "J", "R"])
    node12 = Node("L", ["E", "M", "R"])
    node13 = Node("M", ["C", "G", "L"])
    node14 = Node("N", ["C", "F", "O"])
    node15 = Node("O", ["H", "N", "P"])
    node16 = Node("P", ["D", "J", "O"])
    node17 = Node("Q", ["D", "I", "R"])
    node18 = Node("R", ["K", "L", "Q"])

    second_blanusa_snark.add_node(node1)
    second_blanusa_snark.add_node(node2)
    second_blanusa_snark.add_node(node3)
    second_blanusa_snark.add_node(node4)
    second_blanusa_snark.add_node(node5)
    second_blanusa_snark.add_node(node6)
    second_blanusa_snark.add_node(node7)
    second_blanusa_snark.add_node(node8)
    second_blanusa_snark.add_node(node9)
    second_blanusa_snark.add_node(node10)
    second_blanusa_snark.add_node(node11)
    second_blanusa_snark.add_node(node12)
    second_blanusa_snark.add_node(node13)
    second_blanusa_snark.add_node(node14)
    second_blanusa_snark.add_node(node15)
    second_blanusa_snark.add_node(node16)
    second_blanusa_snark.add_node(node17)
    second_blanusa_snark.add_node(node18)

    return second_blanusa_snark


def create_second_loupekine_snark():
    second_loupekine_snark = Graph()

    node1 = Node("A", ["C", "E", "K"])
    node2 = Node("B", ["D", "F", "O"])
    node3 = Node("C", ["A", "H", "L"])
    node4 = Node("D", ["B", "G", "L"])
    node5 = Node("E", ["A", "J", "N"])
    node6 = Node("F", ["B", "I", "N"])
    node7 = Node("G", ["D", "H", "K"])
    node8 = Node("H", ["C", "G", "M"])
    node9 = Node("I", ["F", "J", "M"])
    node10 = Node("J", ["E", "I", "O"])
    node11 = Node("K", ["A", "G", "U"])
    node12 = Node("L", ["C", "D", "Q"])
    node13 = Node("M", ["H", "I", "P"])
    node14 = Node("N", ["E", "F", "R"])
    node15 = Node("O", ["B", "J", "V"])
    node16 = Node("P", ["M", "S", "T"])
    node17 = Node("Q", ["L", "R", "T"])
    node18 = Node("R", ["N", "Q", "S"])
    node19 = Node("S", ["P", "R", "U"])
    node20 = Node("T", ["P", "Q", "V"])
    node21 = Node("U", ["K", "S", "V"])
    node22 = Node("V", ["O", "T", "U"])

    second_loupekine_snark.add_node(node1)
    second_loupekine_snark.add_node(node2)
    second_loupekine_snark.add_node(node3)
    second_loupekine_snark.add_node(node4)
    second_loupekine_snark.add_node(node5)
    second_loupekine_snark.add_node(node6)
    second_loupekine_snark.add_node(node7)
    second_loupekine_snark.add_node(node8)
    second_loupekine_snark.add_node(node9)
    second_loupekine_snark.add_node(node10)
    second_loupekine_snark.add_node(node11)
    second_loupekine_snark.add_node(node12)
    second_loupekine_snark.add_node(node13)
    second_loupekine_snark.add_node(node14)
    second_loupekine_snark.add_node(node15)
    second_loupekine_snark.add_node(node16)
    second_loupekine_snark.add_node(node17)
    second_loupekine_snark.add_node(node18)
    second_loupekine_snark.add_node(node19)
    second_loupekine_snark.add_node(node20)
    second_loupekine_snark.add_node(node21)
    second_loupekine_snark.add_node(node22)

    return second_loupekine_snark


def create_goldberg_snark():
    goldberg_snark = Graph()

    node1 = Node("A", ["B", "E", "C"])
    node2 = Node("B", ["A", "F", "D"])
    node3 = Node("C", ["A", "J", "G"])
    node4 = Node("D", ["B", "H", "K"])
    node5 = Node("E", ["W", "A", "I"])
    node6 = Node("F", ["L", "B", "Y"])
    node7 = Node("G", ["I", "O", "C"])
    node8 = Node("H", ["L", "D", "Q"])
    node9 = Node("I", ["E", "M", "G"])
    node10 = Node("J", ["C", "M", "AB"])
    node11 = Node("K", ["AC", "D", "N"])
    node12 = Node("L", ["F", "N", "H"])
    node13 = Node("M", ["I", "J", "N"])
    node14 = Node("N", ["K", "L", "M"])
    node15 = Node("O", ["G", "P", "T"])
    node16 = Node("P", ["O", "U", "H"])
    node17 = Node("Q", ["S", "AB", "AI"])
    node18 = Node("R", ["V", "AC", "AH"])
    node19 = Node("S", ["Z", "W", "Q"])
    node20 = Node("T", ["X", "Z", "O"])
    node21 = Node("U", ["X", "P", "AA"])
    node22 = Node("V", ["AA", "R", "Y"])
    node23 = Node("W", ["AF", "E", "S"])
    node24 = Node("X", ["T", "U", "AK"])
    node25 = Node("Y", ["V", "AG", "F"])
    node26 = Node("Z", ["AD", "S", "T"])
    node27 = Node("AA", ["V", "AE", "U"])
    node28 = Node("AB", ["AD", "Q", "J"])
    node29 = Node("AC", ["R", "AE", "K"])
    node30 = Node("AD", ["Z", "AB", "AF"])
    node31 = Node("AE", ["AA", "AC", "AG"])
    node32 = Node("AF", ["W", "AD", "AM"])
    node33 = Node("AG", ["AE", "Y", "AN"])
    node34 = Node("AH", ["R", "AI", "AJ"])
    node35 = Node("AI", ["Q", "AH", "AL"])
    node36 = Node("AJ", ["AH", "AM", "AK"])
    node37 = Node("AK", ["X", "AJ", "AL"])
    node38 = Node("AL", ["AI", "AN", "AK"])
    node39 = Node("AM", ["AF", "AJ", "AN"])
    node40 = Node("AN", ["AM", "AG", "AL"])

    goldberg_snark.add_node(node1)
    goldberg_snark.add_node(node2)
    goldberg_snark.add_node(node3)
    goldberg_snark.add_node(node4)
    goldberg_snark.add_node(node5)
    goldberg_snark.add_node(node6)
    goldberg_snark.add_node(node7)
    goldberg_snark.add_node(node8)
    goldberg_snark.add_node(node9)
    goldberg_snark.add_node(node10)
    goldberg_snark.add_node(node11)
    goldberg_snark.add_node(node12)
    goldberg_snark.add_node(node13)
    goldberg_snark.add_node(node14)
    goldberg_snark.add_node(node15)
    goldberg_snark.add_node(node16)
    goldberg_snark.add_node(node17)
    goldberg_snark.add_node(node18)
    goldberg_snark.add_node(node19)
    goldberg_snark.add_node(node20)
    goldberg_snark.add_node(node21)
    goldberg_snark.add_node(node22)
    goldberg_snark.add_node(node23)
    goldberg_snark.add_node(node24)
    goldberg_snark.add_node(node25)
    goldberg_snark.add_node(node26)
    goldberg_snark.add_node(node27)
    goldberg_snark.add_node(node28)
    goldberg_snark.add_node(node29)
    goldberg_snark.add_node(node30)
    goldberg_snark.add_node(node31)
    goldberg_snark.add_node(node32)
    goldberg_snark.add_node(node33)
    goldberg_snark.add_node(node34)
    goldberg_snark.add_node(node35)
    goldberg_snark.add_node(node36)
    goldberg_snark.add_node(node37)
    goldberg_snark.add_node(node38)
    goldberg_snark.add_node(node39)
    goldberg_snark.add_node(node40)

    return goldberg_snark


def create_watkins_snark():
    watkins_snark = Graph()

    node1 = Node("1", ["2", "4", "15"])
    node2 = Node("2", ["1", "3", "7"])
    node3 = Node("3", ["2", "5", "34"])
    node4 = Node("4", ["1", "5", "6"])
    node5 = Node("5", ["3", "4", "8"])
    node6 = Node("6", ["4", "7", "10"])
    node7 = Node("7", ["2", "6", "8"])
    node8 = Node("8", ["5", "7", "11"])
    node9 = Node("9", ["13", "16", "19"])
    node10 = Node("10", ["6", "11", "45"])
    node11 = Node("11", ["8", "10", "12"])
    node12 = Node("12", ["11", "18", "22"])
    node13 = Node("13", ["9", "14", "23"])
    node14 = Node("14", ["13", "15", "20"])
    node15 = Node("15", ["1", "14", "25"])
    node16 = Node("16", ["9", "17", "26"])
    node17 = Node("17", ["16", "18", "21"])
    node18 = Node("18", ["12", "17", "28"])
    node19 = Node("19", ["9", "20", "29"])
    node20 = Node("20", ["14", "19", "24"])
    node21 = Node("21", ["17", "22", "27"])
    node22 = Node("22", ["12", "21", "30"])
    node23 = Node("23", ["13", "24", "29"])
    node24 = Node("24", ["20", "23", "25"])
    node25 = Node("25", ["15", "24", "48"])
    node26 = Node("26", ["16", "27", "50"])
    node27 = Node("27", ["21", "26", "28"])
    node28 = Node("28", ["18", "27", "30"])
    node29 = Node("29", ["19", "23", "31"])
    node30 = Node("30", ["22", "28", "32"])
    node31 = Node("31", ["29", "32", "35"])
    node32 = Node("32", ["30", "31", "37"])
    node33 = Node("33", ["34", "38", "47"])
    node34 = Node("34", ["3", "33", "40"])
    node35 = Node("35", ["31", "36", "41"])
    node36 = Node("36", ["35", "37", "46"])
    node37 = Node("37", ["32", "36", "42"])
    node38 = Node("38", ["33", "39", "43"])
    node39 = Node("39", ["38", "40", "49"])
    node40 = Node("40", ["34", "39", "44"])
    node41 = Node("41", ["35", "42", "45"])
    node42 = Node("42", ["37", "41", "47"])
    node43 = Node("43", ["38", "44", "48"])
    node44 = Node("44", ["40", "43", "50"])
    node45 = Node("45", ["10", "41", "46"])
    node46 = Node("46", ["36", "45", "47"])
    node47 = Node("47", ["33", "42", "46"])
    node48 = Node("48", ["25", "43", "49"])
    node49 = Node("49", ["39", "48", "50"])
    node50 = Node("50", ["26", "44", "49"])

    watkins_snark.add_node(node1)
    watkins_snark.add_node(node2)
    watkins_snark.add_node(node3)
    watkins_snark.add_node(node4)
    watkins_snark.add_node(node5)
    watkins_snark.add_node(node6)
    watkins_snark.add_node(node7)
    watkins_snark.add_node(node8)
    watkins_snark.add_node(node9)
    watkins_snark.add_node(node10)
    watkins_snark.add_node(node11)
    watkins_snark.add_node(node12)
    watkins_snark.add_node(node13)
    watkins_snark.add_node(node14)
    watkins_snark.add_node(node15)
    watkins_snark.add_node(node16)
    watkins_snark.add_node(node17)
    watkins_snark.add_node(node18)
    watkins_snark.add_node(node19)
    watkins_snark.add_node(node20)
    watkins_snark.add_node(node21)
    watkins_snark.add_node(node22)
    watkins_snark.add_node(node23)
    watkins_snark.add_node(node24)
    watkins_snark.add_node(node25)
    watkins_snark.add_node(node26)
    watkins_snark.add_node(node27)
    watkins_snark.add_node(node28)
    watkins_snark.add_node(node29)
    watkins_snark.add_node(node30)
    watkins_snark.add_node(node31)
    watkins_snark.add_node(node32)
    watkins_snark.add_node(node33)
    watkins_snark.add_node(node34)
    watkins_snark.add_node(node35)
    watkins_snark.add_node(node36)
    watkins_snark.add_node(node37)
    watkins_snark.add_node(node38)
    watkins_snark.add_node(node39)
    watkins_snark.add_node(node40)
    watkins_snark.add_node(node41)
    watkins_snark.add_node(node42)
    watkins_snark.add_node(node43)
    watkins_snark.add_node(node44)
    watkins_snark.add_node(node45)
    watkins_snark.add_node(node46)
    watkins_snark.add_node(node47)
    watkins_snark.add_node(node48)
    watkins_snark.add_node(node49)
    watkins_snark.add_node(node50)

    return watkins_snark
